version: 2

models:
  - name: stg_product
    columns: 
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sales_data
    columns:
      - name: order_id
        tests:
          - not_null

  - name: dimensional_model
    columns: 
      - name: channel
        tests:
          - accepted_values:
              values:
                - Distributor
                - Online
                - Retail


