version: 2

models:
  - name: stg_product
    columns: 
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sales_data
    columns:
      - name: ordernumber
        tests:
          - not_null
      - name: channel
        tests:
          - accepted_values:
              values:
                - distributor
                - online
                - retail